// <auto-generated />
namespace E4Storage.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BeltPICStockCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeltPICStockCard));
        
        string IMigrationMetadata.Id
        {
            get { return "202310012317011_BeltPICStockCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
