// <auto-generated />
namespace E4Storage.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BeltPICStockCard2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeltPICStockCard2));
        
        string IMigrationMetadata.Id
        {
            get { return "202310012349185_BeltPICStockCard2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
