// <auto-generated />
namespace E4Storage.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StockIn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockIn));
        
        string IMigrationMetadata.Id
        {
            get { return "202401140227014_StockIn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
