// <auto-generated />
namespace Inventory.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Manifest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manifest));
        
        string IMigrationMetadata.Id
        {
            get { return "202402111000255_Manifest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
